my_comment = "This is my short comment"

print(len(my_comment))
print()
print(my_comment.upper())
print()
print(my_comment.join("jdsj"))
print()
print(my_comment.title())
print()
print(my_comment.lower())
print()
print(my_comment.casefold())
print()
print(my_comment.count(" "))
print()
print(my_comment.replace("my", "our"))
print()
print(my_comment.capitalize())
print()
print(my_comment[:10])